### ISSUE TITLE
Is there a way to run only secuirty updates run?

### ISSUE THREAD

**Issue by burakcoskunn** [homebysix/install-or-defer#35]
Hello sir, first of all thank you a lot for this script.

your script working well for run all updates OS and Security updates. Is there a way run only security updates like i am using following script for security updates;
https://github.com/jamf/Jamf-Nation-Scripts/blob/master/Apple_Software_Update_Search_v2.sh

**Comment by homebysix** [comment]
Hi @burakcoskunn - If I understand correctly, you want to use install-or-defer only for security updates and not for macOS updates?

Short answer: no. This incarnation of the script is meant to install all updates listed as `Recommended: YES` or `Action: restart` in the `softwareupdate -l` output.

However, due to the fact that most security updates require you to first have the latest macOS updates already installed, you could probably simulate the behavior you desire using the Jamf smart group you use for scoping. For example, you can target only the Macs that require Security Update 2019-001 for Mojave using this criteria:

__Critical Update Needed: Security Update 2019-001 Mojave__

- `Operating System Version` `is` `10.14.6`
- `and` `Operating System Build` `is not` `18G1012`

However, be careful with that scope, because when a build greater than `18G1012` comes out, those newer builds may become false-positives. Regular expressions may help avoid this, but I don't have a foolproof one off the top of my head.

If you _only_ want to install specific updates, then the install-or-defer script probably won't give you what you want without significant customization.

**Comment by burakcoskunn** [comment]
Clear sir. Thanks a lot for your time.
